#-*-mode:snakemake-*-
import glob
import os

#configfile:
#    'config.yaml'

include:
    '../small-rna.sm'
    
SAMPLES = list(config['samples'].keys())

MIRGE_DB = ['mirbase', 'mirnadb']

if config['filter']['quant'] == 'unitas':
    rule test:
        input:
            expand(rules.unitas.output, sample=SAMPLES)
elif config['filter']['quant'] == 'mirge':
    rule test:
        input:
            rules.mirge_all.output
elif config['filter']['quant'] == 'quickmirseq':
    rule test:
        input:
            rules.quickmirseq.output
