#-*-mode:snakemake-*-
import glob
import os

#configfile:
#    'config.yaml'

include:
    '../small-rna.sm'
    
SAMPLES = list(config['samples'].keys())

MIRGE_DB = ['mirbase', 'mirnadb']

rule test_unitas:
    input:
        expand(rules.unitas.output, sample=SAMPLES)
