From:nfcore/base
Bootstrap:docker

%labels
    MAINTAINER Arnar Flatberg <arnar.flatberg@gmail.com>
    DESCRIPTION Singularity image containing all requirements for small-rna pipeline
    VERSION 0.1.0


%post
    /opt/conda/bin/conda --add channels defaults
    /opt/conda/bin/conda --add channels r
    /opt/conda/bin/conda --add channels bioconda
    /opt/conda/bin/conda --add channels conda-forge
    /opt/conda/bin/conda install -y bowtie bowtie2 fastqc fastp atropos sortmerna bbmap
    /opt/conda/bin/conda clean -a
