From:nfcore/base
Bootstrap:docker

%labels
    MAINTAINER Arnar Flatberg <arnar.flatberg@gmail.com>
    DESCRIPTION Singularity image containing all requirements for small-rna pipeline
    VERSION 0.1.0

%files
    environment.yml /

%post
    /opt/conda/bin/conda env update -n root -f /environment.yml
    /opt/conda/bin/conda clean -a
